# Dirty Cafe Sales Dataset
## Overview
- The Dirty Cafe Sales dataset contains 10,000 rows of synthetic data representing sales transactions in a cafe. This dataset is intentionally "dirty," with missing values, inconsistent data, and errors introduced to provide a realistic scenario for data cleaning and exploratory data analysis (EDA). It can be used to practice cleaning techniques, data wrangling, and feature engineering.

## File Information
- File Name: dirty_cafe_sales.csv
- Number of Rows: 10,000
- Number of Columns: 8

### Link: https://www.kaggle.com/datasets/ahmedmohamed2003/cafe-sales-dirty-data-for-cleaning-training

In [1]:
import pandas as pd 
import numpy as np
from pathlib import Path 
from numpy import int32, str_, int64,float32, float64

In [2]:
PROJECT_ROOT = Path.cwd().parent
print("Project Root Directory = ", PROJECT_ROOT)
print("\n")

DATA_DIR = PROJECT_ROOT / "data" / "dirty_cafe_sales.csv" 
print("Data Directory = ", DATA_DIR, end="\n")

data = pd.read_csv(DATA_DIR)
data

Project Root Directory =  c:\Users\user\OneDrive\Desktop\EDA-Practice\sales_data_cleaning


Data Directory =  c:\Users\user\OneDrive\Desktop\EDA-Practice\sales_data_cleaning\data\dirty_cafe_sales.csv

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [3]:
def print_basic_info(df):
    print("Columns that contain NaN values are:\n")
    print(df.isnull().any(axis=0),end="\n\n")

    print("Number of NaN values in each column are:\n")
    print(df.isnull().sum()) 


    print("\nData type of each column:\n")
    print(df.dtypes)

print_basic_info(data)

Columns that contain NaN values are:

Transaction ID      False
Item                 True
Quantity             True
Price Per Unit       True
Total Spent          True
Payment Method       True
Location             True
Transaction Date     True
dtype: bool

Number of NaN values in each column are:

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

Data type of each column:

Transaction ID      str
Item                str
Quantity            str
Price Per Unit      str
Total Spent         str
Payment Method      str
Location            str
Transaction Date    str
dtype: object

In [4]:
# Normalizing the data. For example, the dtypes of each column are string, so i would prefer to have prices in int32 or int64.
# Similarly the naming convention should be all lowercase letters, preferrably no gaps , all the gaps should be filled with _. 

def normalize_data(df):

    df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(r"\s+","_",regex=True)
    )

    # Also change the values inside the payment_method with the same naming convention
    df["payment_method"] = (
        df["payment_method"]
        .str.lower()
        .str.strip()
        .str.replace(r"\s+","_",regex=True)
    )

    df["location"] = (
        df["location"]
        .str.strip()
        .str.lower()
        .str.replace(r"\s+","_",regex=True)
    )

    df["item"] = (
        df["item"]
        .str.lower()
        .str.strip()
        .str.replace(r"\s+","_",regex=True)
    )


    # Also conver the price containing columns to numeric dtype. 
    df["price_per_unit"] = pd.to_numeric(df["price_per_unit"], errors='coerce')
    df["quantity"] = pd.to_numeric(df["quantity"], errors = "coerce")
    df["total_spent"] = pd.to_numeric(df["total_spent"], errors = "coerce")
    df["transaction_date"] = pd.to_datetime(df["transaction_date"], errors="coerce")


    # After converting column values to numeric values, replace any NaN's with mean of that column. 
    df["price_per_unit"] = df["price_per_unit"].fillna(df["price_per_unit"].mean())
    df["quantity"] = df["quantity"].fillna(df["quantity"].mean())
    df["total_spent"] = df["total_spent"].fillna(df["total_spent"].mean())

copy_data = data.copy()
normalize_data(copy_data)
copy_data.head()

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,coffee,2.0,2.0,4.000000,credit_card,takeaway,2023-09-08
1,TXN_4977031,cake,4.0,3.0,12.000000,cash,in-store,2023-05-16
2,TXN_4271903,cookie,4.0,1.0,8.924352,credit_card,in-store,2023-07-19
3,TXN_7034554,salad,2.0,5.0,10.000000,unknown,unknown,2023-04-27
4,TXN_3160411,coffee,2.0,2.0,4.000000,digital_wallet,in-store,2023-06-11